### ISSUE TITLE
Gatsby Previews Plugin does not work with categories yet

### ISSUE THREAD

**Issue by cmarabate** [flotiq/gatsby-starter-products-with-categories#1]
I think having categories might have complicated things because when I go in and edit a product and then click "Open preview" it takes me to https://build-c5ce65a2-57ea-4ee2-b458-9fff7d8a7f66.gtsb.io/product-slug instead of https://build-c5ce65a2-57ea-4ee2-b458-9fff7d8a7f66.gtsb.io/category-slug/product-slug. It doesn't add the slug for the category the product I am editing belongs to into the URL.

**Comment by CiotkaCierpienia** [comment]
Hi @cmarabate, we've fixed our plugin to cope with the more complicated URLs. Sorry for the inconvenience. If you continue to experience any problems, please contact us.
